"""adds stores table

Revision ID: 11e9dae8446e
Revises: 9a41a1b1a478
Create Date: 2023-10-04 18:06:08.240586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e9dae8446e'
down_revision: Union[str, None] = '9a41a1b1a478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('stores', 'address_line_2')
    op.drop_column('stores', 'address_line_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('address_line_1', sa.VARCHAR(), nullable=True))
    op.add_column('stores', sa.Column('address_line_2', sa.VARCHAR(), nullable=True))
    op.drop_column('stores', 'address')
    # ### end Alembic commands ###
